#!/usr/bin/env python3
"""
Stage newer game files from the live install into the repo's release tree.

For every game file already curated into `release/OblivionRemastered/`, this
finds the counterpart at the same relative path in the live game folder and,
if the live file is BOTH newer (mtime) AND different (SHA-256), stages it into
the repo. It only ever pulls files that are already tracked in `release/` --
the live folder holds the whole game plus unrelated mods, none of which are
touched.

Dry-run by default: it reports what WOULD change without writing anything.
Pass --apply to perform the copies.

SyncMap redirect (the one exception):
    The repo's Deluxe SyncMap copy
        .../Data/OptionalPatches/SyncMap - DeluxeEdition/Oscuro's_Oblivion_Overhaul.ini
    is sourced from the live default-location file
        .../Data/SyncMap/Oscuro's_Oblivion_Overhaul.ini
    The repo's own .../Data/SyncMap/Oscuro's_Oblivion_Overhaul.ini (the
    non-Deluxe variant, generated by sync_syncmap.py from the Deluxe copy) is
    left untouched -- the live SyncMap ini's only destination is the Deluxe copy.

Out of scope (handled later by release.py): regenerating `.md` co-files and
`.records/` inventories, manifest hashing, and the non-Deluxe SyncMap variant.
This script only GATHERS; run release.py once everything is staged.

Usage:
    python scripts/gather_live.py                 # dry-run, report only
    python scripts/gather_live.py --apply         # perform the copies
    python scripts/gather_live.py --tag alpha91   # report tag (default: alpha91)
    python scripts/gather_live.py --game-root "C:/.../Oblivion Remastered/OblivionRemastered"
    python scripts/gather_live.py --report work/alpha91_gathered.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath

# --- Paths -----------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
RELEASE_ROOT = REPO_ROOT / "release" / "OblivionRemastered"
DEFAULT_GAME_ROOT = Path(
    r"C:\games\Steam\steamapps\common\Oblivion Remastered\OblivionRemastered"
)

# Relative POSIX paths (from the OblivionRemastered/ root).
DELUXE_INI_REL = (
    "Content/Dev/ObvData/Data/OptionalPatches/"
    "SyncMap - DeluxeEdition/Oscuro's_Oblivion_Overhaul.ini"
)
DEFAULT_SYNCMAP_INI_REL = (
    "Content/Dev/ObvData/Data/SyncMap/Oscuro's_Oblivion_Overhaul.ini"
)
_OPT = "Content/Dev/ObvData/Data/OptionalPatches"
_DATA = "Content/Dev/ObvData/Data"
_BEGONE_CFG = "Binaries/Win64/ue4ss/Mods/Begone/Config"

# Redirects: repo release-relative path -> live game-relative path, for files
# the install keeps at a different location/name than the repo layout does.
# Without an entry here the source is the identical relative path (the default).
REDIRECTS = {
    # The Deluxe SyncMap copy is sourced from the live default-location ini.
    DELUXE_INI_REL: DEFAULT_SYNCMAP_INI_REL,
    # Optional patch ESPs: the repo stages them under OptionalPatches/, but the
    # live install activates them directly in the Data/ load folder.
    f"{_OPT}/OOO_DeluxeEdition.esp": f"{_DATA}/OOO_DeluxeEdition.esp",
    f"{_OPT}/OOO_OOMC_Compatibility_Patch.esp":
        f"{_DATA}/OOO_OOMC_Compatibility_Patch.esp",
    f"{_OPT}/OOO_UnlimitedRingsReduxPatch.esp":
        f"{_DATA}/OOO_UnlimitedRingsReduxPatch.esp",
    f"{_OPT}/OOO_UORP.esp": f"{_DATA}/OOO_UORP.esp",
    # Begone config: live uses a version-stamped filename; repo keeps the plain
    # name. Track the current (v3) live file.
    f"{_BEGONE_CFG}/OscurosOblivionOverhaul.json":
        f"{_BEGONE_CFG}/OscurosOblivionOverhaul.v3.json",
}

# Repo-metadata artifacts that have no live counterpart and must be skipped.
SKIP_SUFFIXES = (".md", ".working")
SKIP_NAMES = (".gitkeep",)


# --- Helpers ---------------------------------------------------------------

def is_metadata(rel: PurePosixPath) -> bool:
    """True for repo-only artifacts: co-files, .records/ contents, scratch."""
    if rel.name in SKIP_NAMES:
        return True
    if rel.suffix in SKIP_SUFFIXES:
        return True
    if any(part.endswith(".records") for part in rel.parts):
        return True
    return False


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def iso(ts: float) -> str:
    return datetime.fromtimestamp(ts, tz=timezone.utc).isoformat()


def human(n: int) -> str:
    units = ["B", "KiB", "MiB", "GiB"]
    f = float(n)
    for u in units:
        if f < 1024 or u == units[-1]:
            return f"{f:,.0f} {u}" if u == "B" else f"{f:.1f} {u}"
        f /= 1024
    return f"{n} B"


def source_for(rel: PurePosixPath, game_root: Path) -> Path:
    """Map a release-relative path to its live source, honoring redirects."""
    live_rel = REDIRECTS.get(rel.as_posix(), rel.as_posix())
    return game_root / Path(live_rel)


# --- Core ------------------------------------------------------------------

def gather(game_root: Path, apply: bool):
    entries = []
    counts = {
        "updated": 0,
        "up-to-date": 0,
        "stale-mtime": 0,
        "no-source": 0,
        "skipped-managed": 0,
    }

    for dest in sorted(RELEASE_ROOT.rglob("*")):
        if not dest.is_file():
            continue
        rel = PurePosixPath(dest.relative_to(RELEASE_ROOT).as_posix())
        if is_metadata(rel):
            continue

        # The non-Deluxe SyncMap ini is owned by sync_syncmap.py -- never synced.
        if rel.as_posix() == DEFAULT_SYNCMAP_INI_REL:
            counts["skipped-managed"] += 1
            entries.append({"rel": rel.as_posix(), "state": "skipped-managed",
                            "note": "owned by sync_syncmap.py"})
            continue

        src = source_for(rel, game_root)
        if not src.is_file():
            counts["no-source"] += 1
            entries.append({"rel": rel.as_posix(), "state": "no-source",
                            "source_rel": src.relative_to(game_root).as_posix()})
            continue

        dst_stat, src_stat = dest.stat(), src.stat()
        dst_sha, src_sha = sha256(dest), sha256(src)

        if dst_sha == src_sha:
            counts["up-to-date"] += 1
            entries.append({"rel": rel.as_posix(), "state": "up-to-date"})
            continue

        # Content differs -- only copy when the live file is also newer.
        newer = src_stat.st_mtime > dst_stat.st_mtime
        state = "updated" if newer else "stale-mtime"
        entry = {
            "rel": rel.as_posix(),
            "state": state,
            "source_rel": src.relative_to(game_root).as_posix(),
            "old_sha": dst_sha,
            "new_sha": src_sha,
            "old_size": dst_stat.st_size,
            "new_size": src_stat.st_size,
            "old_mtime": iso(dst_stat.st_mtime),
            "new_mtime": iso(src_stat.st_mtime),
            "copied": False,
        }
        if state == "updated":
            counts["updated"] += 1
            if apply:
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dest)  # preserve live mtime for future runs
                entry["copied"] = True
        else:
            counts["stale-mtime"] += 1
        entries.append(entry)

    return entries, counts


# --- Reporting -------------------------------------------------------------

def print_report(entries, counts, apply: bool):
    verb = "Copied" if apply else "Would update"
    print(f"{'STATE':<16} {'PATH'}")
    print("-" * 72)
    for e in entries:
        if e["state"] == "up-to-date":
            continue
        line = f"{e['state']:<16} {e['rel']}"
        if e["state"] in ("updated", "stale-mtime"):
            line += (f"\n{'':<16} {human(e['old_size'])} -> {human(e['new_size'])}"
                     f"   ({e['old_mtime']} -> {e['new_mtime']})")
        print(line)
    print("-" * 72)
    print(f"{verb}: {counts['updated']}   "
          f"up-to-date: {counts['up-to-date']}   "
          f"stale-mtime (differs, not newer): {counts['stale-mtime']}   "
          f"no-source: {counts['no-source']}   "
          f"skipped-managed: {counts['skipped-managed']}")
    if not apply and counts["updated"]:
        print("\nDry-run -- no files written. Re-run with --apply to copy.")
    if counts["stale-mtime"]:
        print("WARNING: files whose content differs but whose live mtime is NOT "
              "newer were left untouched (state 'stale-mtime'). Inspect them.")


def write_json(report_path: Path, tag: str, game_root: Path, apply: bool,
               entries, counts):
    payload = {
        "tag": tag,
        "generated": iso(datetime.now(tz=timezone.utc).timestamp()),
        "applied": apply,
        "game_root": str(game_root),
        "release_root": str(RELEASE_ROOT),
        "counts": counts,
        # Persist everything except no-op up-to-date files.
        "entries": [e for e in entries if e["state"] != "up-to-date"],
    }
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"\nReport written: {report_path}")


# --- CLI -------------------------------------------------------------------

def main(argv=None):
    sys.stdout.reconfigure(encoding="utf-8")
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--apply", action="store_true",
                    help="perform the copies (default: dry-run report only)")
    ap.add_argument("--tag", default="alpha91",
                    help="release tag for the report (default: alpha91)")
    ap.add_argument("--game-root", type=Path, default=DEFAULT_GAME_ROOT,
                    help="live game OblivionRemastered/ folder")
    ap.add_argument("--report", type=Path, default=None,
                    help="JSON report path (default: work/<tag>_gathered.json)")
    args = ap.parse_args(argv)

    game_root = args.game_root.resolve()
    if not game_root.is_dir():
        ap.error(f"game root not found: {game_root}")
    if not RELEASE_ROOT.is_dir():
        ap.error(f"release root not found: {RELEASE_ROOT}")

    report_path = args.report or (REPO_ROOT / "work" / f"{args.tag}_gathered.json")

    entries, counts = gather(game_root, args.apply)
    print_report(entries, counts, args.apply)
    write_json(report_path, args.tag, game_root, args.apply, entries, counts)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
